### ISSUE TITLE
Never mix `yarn` and `npm`

### ISSUE THREAD

**Issue by flexbox** [ccaruyer/spacecraft#1]
https://github.com/ccaruyer/spacecraft/blob/42bec26f2e6a50c0dc85adeef550b1c37ff88f1a/package-lock.json#L1

You should not have a `package-lock` AND a `yarn.lock`

on your README you should stick on 
```
npm install
```
or
```
yarn install
```

If you keep both, you can have a mismatch between the dependencies and lose 1000 years in debugging.

**Comment by ccaruyer** [comment]
J'ai résolut le problème, il s'agissait une fausse manipulation entre plusieurs cmd.
Merci de l'aide !
